# Generated by Django 3.2.4 on 2024-05-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_campaign_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='campaign',
            table='campaigns',
        ),
    ]
