version: '3'

services:
  postgres:
    image: postgres:14
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dnd-weaver
    ports:
      - "5432:5432"