# Generated by Django 3.2.4 on 2024-09-16 18:37

import core.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Modified date')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Enabled or disabled record')),
                ('index', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Monster',
                'verbose_name_plural': 'Monsters',
                'db_table': 'monster',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Modified date')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Enabled or disabled record')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('lvl_requirement', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('story_mode', models.BooleanField(default=False)),
                ('map', models.ImageField(null=True, upload_to=core.utils.uploaded_image_filepath)),
                ('soundtrack', models.FileField(null=True, upload_to=core.utils.uploaded_soundtrack_filepath)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='campaign.campaign')),
            ],
            options={
                'verbose_name': 'Scenario',
                'verbose_name_plural': 'Scenarios',
                'db_table': 'scenario',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Npc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Modified date')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Enabled or disabled record')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, default='', max_length=255)),
                ('race', models.CharField(choices=[('human', 'Human'), ('elf', 'Elf'), ('demi-human', 'demi-Human')], default='human', max_length=20)),
                ('scenario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='npcs', to='scenario.scenario')),
            ],
            options={
                'verbose_name': 'Npc',
                'verbose_name_plural': 'Npcs',
                'db_table': 'npc',
            },
        ),
    ]
