# Generated by Django 3.2.4 on 2024-05-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='story_mode',
            field=models.BooleanField(default=False),
        ),
    ]
