# Generated by Django 3.2.4 on 2024-05-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0003_alter_scenario_story_mode'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='monster',
            table='monsters',
        ),
        migrations.AlterModelTable(
            name='npc',
            table='npcs',
        ),
        migrations.AlterModelTable(
            name='scenario',
            table='scenarios',
        ),
    ]
