# Generated by Django 3.2.4 on 2024-05-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0004_auto_20240510_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='image',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='lvl',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='name',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='background',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='image',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='lvl',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='name',
        ),
    ]
