# Generated by Django 3.2.4 on 2024-05-21 08:07

import app.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0005_auto_20240516_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='background',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='image',
            field=models.ImageField(null=True, upload_to=app.utils.uploaded_image_filepath),
        ),
        migrations.AddField(
            model_name='monster',
            name='lvl',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='monster',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='npc',
            name='background',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='image',
            field=models.ImageField(null=True, upload_to=app.utils.uploaded_image_filepath),
        ),
        migrations.AddField(
            model_name='npc',
            name='lvl',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='npc',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
    ]
