# Generated by Django 3.2.4 on 2024-08-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20240516_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_player',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_dm',
            field=models.BooleanField(default=True),
        ),
    ]
